version: '3.8'

services:
  # BACKEND (Python)
  api:
    build: ./backend
    container_name: mi_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  # FRONTEND (Nginx)
  web:
    build: ./frontend
    container_name: mi_frontend
    ports:
      - "3000:80"
    depends_on:
      - api